version: '3.4'
services:
  graphhopper:
    image: gispo/graphhopper:latest
    volumes:
      - ./data:/data
      - ./:/usr/src/app
    ports:
      - 8989:8989
    entrypoint: ./graphhopper.sh -c /usr/src/app/gh-config.yml -o /data/default-gh/
    command: web -i africa_uganda.pbf
    restart: always
    environment:
      - JVM_OPTS=-Xmx12g -Xms12g
