version: '3.4'
volumes:
  ghdata:
services:
  graphhopper:
    image: harelmazor/graphhopper:1.0-pre33.4.7
    volumes:
      - ghdata:/data
      - ./:/usr/src/app
    ports:
      - 8989:8989
    command: -i - -c /usr/src/app/gh-config.yml -o /data/default-gh/
    restart: always
