version: '3.4'

services:
  website:
    image: israel-hiking
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    volumes:
      - ./IsraelHiking.Web/appsettings.Docker.json:/israelhiking/appsettings.json
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
  graphhopper:
    image: harelmazor/graphhopper:1.0-pre33.4.7
    container_name: graphhopper
    volumes:
      - ghdata:/data
      - ./:/usr/src/app
    ports:
      - 8989:8989
    command: -i - -c /usr/src/app/gh-config.yml -o /data/default-gh/
    restart: always
volumes:
  esdata:
    driver: local
  ghdata:
    driver: local
